### ISSUE TITLE
IntervalSetLib with real numbers

### ISSUE THREAD

**Issue by LucaGaspa** [LucaGaspa/mzn2omt#2]
IntervalSetLib does not provide real number set management.
Currently we support only MiniZinc files with no float range limitation (e.g. "var 1.2..1.5: x;")

Clarification:
We support real variables with no range limitation (e.g. "var of float: x;")

**Comment by PatrickTrentin88** [comment]
I can't reproduce it:

```
var int: x;
var 0..5: y;
var float: z;
var 1.2..1.5: t;
solve satisfy;
```

results in

```
(declare-fun x () Int )
(declare-fun y () Int )
(declare-fun z () Bool )
(declare-fun t () Int )
```

which commit are you working on?

**Comment by LucaGaspa** [comment]
I was getting that same result on a ubuntu 16.04 VM.
Now it's ok. Try it :D

**Comment by PatrickTrentin88** [comment]
I think this issue can be closed, if there are other things you would like to get my focus on, please open some more. :+1:

**Comment by LucaGaspa** [comment]
Thank you for your refactoring, it's really appreciated!
